name: Run tests

on:
  push:
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 4 * * 0' # run at 4 AM UTC every Sunday

jobs:
  tests:
    name: Running tests

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y git-lfs
        git lfs install
        pip install --upgrade pip
        pip install git+https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake.git@v2.6.5
        pip install -e .[test]
        pip install pytest-cov
    - name: Test with pytest
      run: |
        pytest --durations=0 tests/ --cov=wifa --cov-report=xml tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
