name: Run tests

on:
  push:
  pull_request:
    branches:
      - main
      - dev
      - windio-merge
  schedule:
    - cron: '0 4 * * 0' # run at 4 AM UTC every Sunday

jobs:

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"  # Use latest version for pre-commit
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  tests:
    name: Running tests

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - run: uv venv --python ${{ matrix.python-version }}
    - run: uv pip install -e .[test]
    - run: uv run pytest --durations=0 tests/
    - name: Minimize uv cache
      run: uv cache prune --ci
